import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/pagination";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/types/Providers";
import FavoriteContextProvider from "@/context/FavoriteContext";

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by Mohamed Abdelhamed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto antialiased">
        <Providers>
          <FavoriteContextProvider> {/* 👈 لف المشروع كله */}
            <Navbar />
            <main>{children}</main>
            <Toaster />
          </FavoriteContextProvider>
        </Providers>
        {/* Footer */}
      </body>
    </html>
  );
}
